version: 0.2

environment_variables:
  plaintext:
    APP_NAME: laravel-hands-on-app
phases:
  install:
    commands:
      ## cd
      ## laravelのリポジトリに入っておく
      - cd laravel

      - echo install started on `date`

      ## Dockerデーモンを起動し、正常に起動が終わるまで待つ。
      - echo executed dockerd on `date`
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo dockerd started

      ## MySQLをインストールし、正常に起動できるまで待つ
      - docker-compose up -d

      ## composer実行
      - composer install --dev
  pre_build:
    commands:
      ## .env.dev -> .envにリネーム
      - mv .env.dev .env
  build:
    commands:
      ## Dockerイメージのビルド
      - echo Building the Docker image...
    
      ## キャッシュを利用したい場合
      ## - docker pull $IMAGE_REPOSITORY_NAME:$APP_NAME && CACHE_OPTION="--cache-from $IMAGE_REPOSITORY_NAME:$APP_NAME" || true
      ## - docker build $CACHE_OPTION -t $IMAGE_REPOSITORY_NAME:$APP_NAME .

      - docker build -t $APP_NAME .

      ## 構築したイメージ上で'composer run ci-check'しテスト実行
      - echo Testing the source code...
      - echo Build started on `date`
      - docker run -e "DB_HOST=127.0.0.1" -e "DB_PORT=3306" -e "DB_DATABASE=mysql" -e "DB_USERNAME=homestead" -e "DB_PASSWORD=password" --network=host --entrypoint="composer" $APP_NAME run ci-check
