version: '3'
services:
  test-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3306
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6380:6379